name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Example: If using Node.js for a frontend project
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Specify your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Replace with your build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Replace with your build output directory
          publish_branch: gh-pages # The branch GitHub Pages deploys from
